### ISSUE TITLE
Add a logger

### ISSUE THREAD

**Issue by PierreZ** [PierreZ/goStatic#47]
All printing is done through fmt.Println(""). We should add a logger and replace all fmt.Print calls.

We can use Zap, Logrus, or another.

**Comment by krishnaindani** [comment]
hey, could I grab this to work on?

**Comment by PierreZ** [comment]
Sure, have fun 👍

**Comment by krishnaindani** [comment]
I see logrus is in maintenance mode currently, so I was thinking to use Zap. Also will use structured logging. Do you have any preferences/suggestions?

**Comment by PierreZ** [comment]
Let's use zap 🚀

**Comment by krishnaindani** [comment]
what do you think is the right way to go here, 

1. Declare global logger and use that, since all I see is in the main package. 
2. Declare logger and pass it around functions to log. This might need to change function definition to get logger as input. 

Or there is any other way you would like to suggest?

**Comment by PierreZ** [comment]
I'm ok with `1.` for now, as long as it is configured at runtime :+1:

**Comment by krishnaindani** [comment]
sounds good.

**Comment by PierreZ** [comment]
Key @krishnaindani, just checking in, do you need some help with the issue? 🙂

**Comment by deranjer** [comment]
This should be completed with #49

**Comment by PierreZ** [comment]
You are right, closing the issue.
